### ISSUE TITLE
[PE-D][Tester C] [edit][tag] Abuse of tag word limit

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F08-4/tp#202]
![Screenshot 2024-11-08 at 4.28.43 PM.png](https://raw.githubusercontent.com/martout2002/ped/main/files/ad553dc0-6efa-4dbf-a57d-3b552d3eddb4.png)

am i supposed to be able to tag with so many characters, it seems abit hard to read, minor issue

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: martout2002/ped#3

**Comment by O-Darren** [comment]
enhancement
